alphabetical = {}
alphabetical[0] = ""
alphabetical[1] = ""
alphabetical[2] = ""
alphabetical[3] = ""
alphabetical[4] = ""
alphabetical[5] = ""
alphabetical[6] = ""
alphabetical[7] = ""
alphabetical[8] = ""
alphabetical[9] = ""
alphabetical[10] = ""
alphabetical[11] = ""
alphabetical[12] = ""
alphabetical[13] = ""
alphabetical[14] = ""
alphabetical[15] = ""
alphabetical[16] = ""
alphabetical[17] = ""
alphabetical[18] = ""
alphabetical[19] = ""
alphabetical[20] = ""
alphabetical[21] = ""
alphabetical[22] = ""
alphabetical[23] = ""
alphabetical[24] = ""
alphabetical[25] = ""
alphabetical[26] = ""
alphabetical[27] = ""
alphabetical[28] = ""
alphabetical[29] = ""


chronological = {}
chronological[0] = ""
chronological[1] = ""
chronological[2] = ""
chronological[3] = ""
chronological[4] = ""
chronological[5] = ""
chronological[6] = ""
chronological[7] = ""
chronological[8] = ""
chronological[9] = ""
chronological[10] = ""
chronological[11] = ""
chronological[12] = ""
chronological[13] = ""
chronological[14] = ""
chronological[15] = ""
chronological[16] = ""
chronological[17] = ""
chronological[18] = ""
chronological[19] = ""
chronological[20] = ""
chronological[21] = ""
chronological[22] = ""
chronological[23] = ""
chronological[24] = ""
chronological[25] = ""
chronological[26] = ""
chronological[27] = ""
chronological[28] = ""
chronological[29] = ""

print(len(alphabetical))
for x in range(1, len(alphabetical)):
    print(x)